# Copyright 2019-2020 Hewlett Packard Enterprise Development LP

FROM cray/reds-base

# Run test coverage...
RUN set -ex && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/cmd/reds && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/internal/snmp/common && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/internal/snmp/dell && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/internal/storage && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/internal/storage/etcd && \
    go test -cover -v stash.us.cray.com/HMS/hms-reds/internal/mapping
